# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terragrunt-multi-environments-jefta"
    encrypt = true
    key     = "environments/prod/terraform.tfstate"
    region  = "us-east-1"
  }
}
