# github action code to deploy code in different environments

name: 'Deploy to Environment'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      terraform_command:
        description: 'Select the Terraform command to run'
        required: true
        default: 'init'
        type: choice
        options:
          - init
          - plan
          - apply
          - destroy

defaults:
  run:
    shell: bash

jobs:
  validate:
    # validate if we push to main | staging | dev
    uses: ./.github/workflows/validate.yaml
    with:
        terraform_command: ${{ github.event.inputs.terraform_command || 'init' }}
        environment: ${{ github.event.inputs.environment || 'dev'}}
    secrets: inherit   