# github action code to deploy code in different environments

name: 'Deploy to Environment'

on:
  push:
    branches:
      - main
      - dev
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      terraform_command:
        description: 'Select the Terraform command to run'
        required: true
        default: 'apply'
        type: choice
        options:
          - init
          - plan
          - apply
          - destroy

defaults:
  run:
    shell: bash

jobs:
  validate:
    # validate if we push to main | staging | dev
    uses: ./.github/workflows/validate.yaml
    with:
        terraform_command: ${{ inputs.terraform_command }}
        environment: ${{ inputs.environment }}