# github action code to deploy code in different environments

name: 'Destroy Resources'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      terraform_command:
        description: 'Select the Terraform command to run'
        required: true
        default: 'destroy'
        type: choice
        options:
          - destroy

defaults:
  run:
    shell: bash

jobs:
    validate:
        runs-on: ubuntu-latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

        steps:
            # checkout the code to the github runner
            - name: Checkout Code
              uses: actions/checkout@v3

            # set up Terragrunt
            - name: Install Terragrunt
              uses: gruntwork-io/terragrunt-action@v3
              with:
                tg_version: "0.83.1"      # latest Terragrunt
                tofu_version: "1.10.0"    # latest OpenTofu


            # Terragrunt Destroy
            - name: terragrunt destroy
              id: destroy
              working-directory: ./terraform/environments/${{ inputs.environment }}
              run: terragrunt destroy -auto-approve